### ISSUE TITLE
Import/Query Custom Resource Objects that already exist

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi-kubernetes#1035]
### Problem description

I am trying to import/query an existing custom resource object that Rancher creates in our Kubernetes cluster so we can make some modifications to it. We are currently using dotnet for our Pulumi stack.

The custom resource object is 
```
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: user
...
```

I was able to find that I can create a new "Pulumi.Kubernetes.ApiExtensions.V1.CustomResourceDefinition()" but this would just create a new CRD. Since the custom resources are dynamic objects in kubernetes based on the custom resource definition I was unable to find a way to import these custom objects.

### Affected product version(s)

v1.12.1

### Suggestions for a fix

N/A

**Comment by lblackstone** [comment]
I verified that this is possible using the TypeScript SDK, but noticed that the `apiextensions.CustomResource` class hasn't been implemented yet for .NET. I've opened #1038 to track that work.

For future reference, this is what the import code looked like for TS:

```ts
new k8s.apiextensions.v1beta1.CustomResourceDefinition("foo", {
    metadata: {
        annotations: {},
        name: "crontabs.stable.example.com",
    },
    spec: {
        group: "stable.example.com",
        versions: [{
            name: "v1",
            served: true,
            storage: true,
        }],
        scope: "Cluster",
        names: {
            plural: "crontabs",
            singular: "crontab",
            kind: "CronTab",
            shortNames: ["ct"],
        }
    },
}, {
    import: "crontabs.stable.example.com"
})

new k8s.apiextensions.CustomResource("foo", {
    apiVersion: "stable.example.com/v1",
    kind: "CronTab",
    metadata: {
        annotations: {},
        name: "my-new-cron-object",
    },
    spec: {
        cronSpec: "* * * * */5",
        image: "my-awesome-cron-image",
    }
}, {
    import: "my-new-cron-object",
})
```
The resources to import were created with `kubectl` using the following YAML:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontabs.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
#  scope: Namespaced
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: crontabs
    # singular name to be used as an alias on the CLI and for display
    singular: crontab
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CronTab
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - ct
---
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
```
