### ISSUE TITLE
Import requires annotations to be specified

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1065]
### Problem description

Importing k8s resources without user-specified annotations still requires the `annotations` field to be specified as an empty map.

For example:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-nginx-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: nginx-ingress-controller
data:
  proxy-buffer-size: "128k"
  proxy-buffers: "8 128k"
```

requires the following code to import:
```ts
new k8s.core.v1.ConfigMap("nginx-nginx-ingress-controller", {
    metadata:{
        annotations: {},
        name: "nginx-nginx-ingress-controller",
        labels: {"k8s-app": "nginx-ingress-controller"},
        namespace:"kube-system"
    },
    data: {
        "proxy-buffer-size": "128k",
        "proxy-buffers": "8 128k"
    }
},{import: "kube-system/nginx-nginx-ingress-controller"});
```

This shouldn't be required, and it frequently trips up our users.
