### ISSUE TITLE
Support user-specified readiness/await logic

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1260]
### Problem description

We already provide readiness/await logic for common k8s resources today, but this doesn't adequately cover CustomResources since each one is different. For k8s operators in particular, it's common to specify a state and then wait for a particular condition to be met before further action is taken.

https://github.com/pulumi/pulumi-kubernetes/issues/912 is one example of this.

In many cases, checking for readiness requires checking a field in a k8s resource against a known value (e.g. "Ready"). It's possible to watch the k8s Event stream for updates, so we should provide some mechanism for users to specify Events + fields of interest and use that as a dependency in the Pulumi resource graph.

Here's an example showing one possible way of implementing this support: https://gist.github.com/lblackstone/d2d1c29507685c0833612988945dedf3

**Comment by marioapardo** [comment]
Can the example be done in the Python SDK? or is it just for JS right now?

**Comment by ghostsquad** [comment]
any news on this front? I feel like this is really important functionality that was made easy in ArgoCD, as they allowed you to write some simple Lua to perform health checking.

https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#custom-health-checks

I feel like if I could figure out, even a temporary work around, to health checks for CRDs, then I could use the Pulumi K8s Operator to deploy Pulumi k8s `stack` resources to k8s clusters, doing so in _order_ based on health, and essentially implement the ArgoCD App of Apps pattern within Pulumi, and further simplify my workflows.

**Comment by lblackstone** [comment]
> any news on this front?

We're still thinking about how to support this generically in the provider.

Relatedly, we recently started factoring out the await logic into a [separate library](https://github.com/pulumi/cloud-ready-checks), which would make it possible to contribute checks for additional resource types. This will also require work on the provider side to make use of any new checks, but I expect that we will eventually support this more dynamically.

**Comment by kralikba** [comment]
Has there been any update to this?
I understand that this is a major design challenge. In my use case, specifying an expected value for a field of the CRD would also be a simple solution. Right now I have to resort to too many hacks using dummy Outputs and a non-pulumi kubernetes client. (I'm using C#)

**Comment by ghostsquad** [comment]
@kralikba what if in the interim, each resource was wrapped in a component resource, which could the object and a [https://www.pulumi.com/registry/packages/command/api-docs/provider/](resource), that called out to a CLI like https://github.com/cakehappens/seaworthy ?

> Seaworthy is your post-apply validation that your K8s resources deployed correctly and are healthy.

This CLI is still just in a POC state.

---

I think the main problem with Pulumi allowing custom health checking, is that in some languages, like Go, you can't serialize functions, and the code that we all write, is just creating a schema of desired state, which is serializable, as just a series of interconnected objects. 

I too am interested to know what kinds of problems still need a solution.

**Comment by jabbrwcky** [comment]
Hey, I stumbled across this issue while looking for a way to wait on cert-manager having issued a certificate before proceeding.

I see the issue with serializing logic, but would it not at least be possible to express resource readiness constraints for resources that implement the [recommended conditions for the status subresource](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties).

The cert-manager Certificate CR does implement status this way, e.g.:

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    pulumi.com/patchForce: 'true'
    pulumi.com/timeoutSeconds: '60'
  name: my-cert
  namespace: zammad-stage-system
spec:
  # ...
status:
  conditions:
    - lastTransitionTime: '2023-01-04T13:37:56Z'
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: 'True'
      type: Ready
  notAfter: '2023-04-04T13:37:56Z'
  notBefore: '2023-01-04T13:37:56Z'
  renewalTime: '2023-03-20T13:37:56Z'
  revision: 1
```

It might just be passed as part of resource options as plain data:

```typescript
const tls = new k8s.apiextensions.CustomResource(`${name}-certificate`, {
    apiVersion: "cert-manager.io/v1",
    kind: "Certificate",
    spec: { /* ... */ }
},{
    readyConditions: [{
        status: 'True',
        type: 'Ready',
        // reason: '...',
    }]
})
```

This way no function serialization would be required for static language support?
