### ISSUE TITLE
crd2pulumi panics on CRD without OpenApi schema

### ISSUE THREAD

**Issue by hazsetata** [pulumi/pulumi-kubernetes#1302]
### Problem description

When trying to run crd2pulumi on a CRD that doesn't contain an OpenApi schema (or on a YAML containing a set of CRDs, and at least one of them doesn't have an OpenApi schema), the tool panics. I compiled it from source, as the released binary had a different problem on the file (`error: invalid apiVersion`).

An example from Ambassador API Gateway I ran into:

```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/name: ambassador
    product: aes
  name: filterpolicies.getambassador.io
spec:
  group: getambassador.io
  names:
    categories:
      - ambassador-crds
    kind: FilterPolicy
    plural: filterpolicies
    shortNames:
      - fp
    singular: filterpolicy
  scope: Namespaced
  version: null
  versions:
    - name: v2
      served: true
      storage: true
    - name: v1beta2
      served: true
      storage: false
    - name: v1beta1
      served: true
      storage: false

```

### Errors & Logs

```
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/pulumi/pulumi-kubernetes/provider/v2/cmd/crd2pulumi/gen.(*PackageGenerator).GetTypes(0xc0005239e8, 0xc00063b3b0)
        /Development/go/src/github.com/pulumi/pulumi-kubernetes/provider/cmd/crd2pulumi/gen/schema.go:62 +0x32f
github.com/pulumi/pulumi-kubernetes/provider/v2/cmd/crd2pulumi/gen.NewPackageGenerator(0xc0002db680, 0x1, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Development/go/src/github.com/pulumi/pulumi-kubernetes/provider/cmd/crd2pulumi/gen/generate.go:200 +0x8c7
github.com/pulumi/pulumi-kubernetes/provider/v2/cmd/crd2pulumi/gen.Generate(0xc000528800, 0x0, 0x0, 0x0, 0xc0002db680, 0x1, 0x4, 0xc000523d00, 0x1ae35d6, 0x2506260)
        /Development/go/src/github.com/pulumi/pulumi-kubernetes/provider/cmd/crd2pulumi/gen/generate.go:89 +0x6a
github.com/pulumi/pulumi-kubernetes/provider/v2/cmd/crd2pulumi/cmd.glob..func2(0x2506260, 0xc0002db680, 0x1, 0x4)
        /Development/go/src/github.com/pulumi/pulumi-kubernetes/provider/cmd/crd2pulumi/cmd/root.go:119 +0xd9
github.com/spf13/cobra.(*Command).execute(0x2506260, 0xc0000320b0, 0x4, 0x4, 0x2506260, 0xc0000320b0)
        /Development/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2506260, 0x0, 0xffffffff, 0xc0000420b8)
        /Development/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Development/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/pulumi/pulumi-kubernetes/provider/v2/cmd/crd2pulumi/cmd.Execute(...)
        /Development/go/src/github.com/pulumi/pulumi-kubernetes/provider/cmd/crd2pulumi/cmd/root.go:131
main.main()
        /Development/go/src/github.com/pulumi/pulumi-kubernetes/provider/cmd/crd2pulumi/main.go:22 +0x2e
```
