### ISSUE TITLE
Python yaml.ConfigFile Resource returning error "Exception: cannot unmarshal output properties: malformed resource reference: id not a string"

### ISSUE THREAD

**Issue by mitchellmaler** [pulumi/pulumi-kubernetes#1367]
### Problem description

Trying to create a PrometheusRule resource using Python yaml.ConfigFile. I provide the name and file path and run up.

### Errors & Logs

`Exception: cannot unmarshal output properties: malformed resource reference: id not a string`

### Affected product version(s)

CLI v2.13.0
pulumi-kubernetes 2.6.3 
pulumi            2.13.0 

### Reproducing the issue
yaml file holding this
```
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: rancher-monitoring
    release: rancher-monitoring
  name: node-custom-rules
spec:
  groups:
    - name: node-custom-rules
      rules:
        - alert: ZombieProcessFound15m
          annotations:
            message: '{{ $value }} zombie processes found on node "{{ $labels.node }}" for 15 minutes.'
          expr: |
            node_processes_state{state="Z"} > 0
          for: 15m
          labels:
            severity: warning
        - alert: NodeRunningOutOfMemory
          expr: (node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes * 100 < 10
          for: 10m
          labels:
            severity: warning
          annotations:
            message: "Node {{ $labels.node }} memory is filling up (< 10% left) at {{ $value }}"
        - alert: NodeDiskOutOfInodes
          expr: node_filesystem_files_free{} / node_filesystem_files{} * 100 < 10
          for: 5m
          labels:
            severity: warning
          annotations:
            message: "Disk {{ $labels.device }} is almost running out of available inodes (< 10% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
        - alert: NodeHighCpuLoad
          expr: 100 - (avg by(node) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            message: "Node {{ $labels.node }} CPU load is > 80% at {{ $value }}"
        - alert: NodeNetworkConntrackUsage80percent
          expr: sort(node_nf_conntrack_entries{job="node-exporter"} > node_nf_conntrack_entries_limit{job="node-exporter"}  * 0.8)
          for: 5m
          labels:
            severity: warning
          annotations:
            message: '{{$labels.node}} has network conntrack entries of {{ $value }} which is more than 80% of maximum limit'
        - alert: NodeEntropyAvailableLow
          expr: node_entropy_available_bits < 300
          for: 5m
          labels:
            severity: warning
          annotations:
            message: '{{$labels.node}} has available entropy bits of {{ $value }} which is less than required of 300'
```

Create resource from it

```python
pulumi_kubernetes.yaml.ConfigFile(
  name="rule",
  file="rule.yml"
)
```
