### ISSUE TITLE
Pulumi up freezes with nginx chart and certain Helm values

### ISSUE THREAD

**Issue by OvervCW** [pulumi/pulumi-kubernetes#1433]
### Problem description

When I deploy the [nginx ingress chart](https://github.com/kubernetes/ingress-nginx) with the following values, Pulumi seems to get stuck when rendering the chart:

```yaml
controller:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - nginx-ingress
          topologyKey: kubernetes.io/hostname
```

The same values work fine when putting them through `helm template` and specifying different values results in a deployment that works fine.

### Errors & Logs

Pulumi simply gets stuck right after rendering some other resources.

### Affected product version(s)

I'm reproducing this with version v2.17.2.

### Reproducing the issue

```python
k8s.helm.v3.Chart(
    "nginx",
    ChartOpts(
        "ingress-nginx/ingress-nginx",
        "ingress",
        version="3.19.0",
        values=values,
    ),
    opts=ResourceOptions(provider=<kubernetes provider here>),
)
```

### Suggestions for a fix

\-
