### ISSUE TITLE
Kubernetes "default" namespace handling

### ISSUE THREAD

**Issue by hazsetata** [pulumi/pulumi-kubernetes#145]
in kubernetes "default" namespace can be omitted from manifests. But if I read the following manifest file:

```
apiVersion: apps/v1
kind: Deployment
metadata:
 name: bzcerts-cert-manager
 namespace: "default"
 ...
```

Pulumi creates the object (internally) with name: default/bzcerts-cert-manager
However if I use this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
 name: bzcerts-cert-manager
 ...
```

Pulumi creates the object (internally) with name: bzcerts-cert-manager

It tripped me up when I try to get some info from the spec:

export const certManager = configGroup.getResource("apps/v1/Deployment", "bzcerts-cert-manager");

It works only with the second manifest format, but it should work the same for both, I think.
