### ISSUE TITLE
Services deployed using Kind: List ignore namespace.

### ISSUE THREAD

**Issue by matteocalabro-tomtom** [pulumi/pulumi-kubernetes#1507]
Hello.

Deploying Traefik using the helm chart shows an unexpected behaviour: everything is deployed correctly into the specified namespace expect the Service; that, goes into `default`. The service won't be able to reach any pod, therefore the deployment fails waiting for the Service to be ready.

I suspect this is because the [chart declares services using the List kind](https://github.com/traefik/traefik-helm-chart/blob/master/traefik/templates/service.yaml):

## Running `pulumi up --diff`:

The Deployment:
```yaml
+ kubernetes:apps/v1:Deployment: (create)
[urn=urn:pulumi:dev::acluster::kubernetes:helm.sh/v3:Chart$kubernetes:apps/v1:Deployment::ingress-traefik/ingress-traefik]
[provider=urn:pulumi:dev::acluster::pulumi:providers:kubernetes::<removed>]
apiVersion: "apps/v1"
kind      : "Deployment"
metadata  : {
    labels   : {
        app.kubernetes.io/instance  : "ingress-traefik"
        app.kubernetes.io/managed-by: "pulumi"
        app.kubernetes.io/name      : "traefik"
        helm.sh/chart               : "traefik-9.18.0"
    }
    name     : "ingress-traefik"
    namespace: "ingress-traefik"
}
spec      : {
...
```

### Expected behavior
```yaml
+ kubernetes:core/v1:Service: (create)
[urn=urn:pulumi:dev::acluster::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::ingress-traefik]
[provider=urn:pulumi:dev::acluster::pulumi:providers:kubernetes::<removed>]
apiVersion: "v1"
kind      : "Service"
metadata  : {
    labels   : {
        app.kubernetes.io/instance  : "ingress-traefik"
        app.kubernetes.io/managed-by: "pulumi"
        app.kubernetes.io/name      : "traefik"
        helm.sh/chart               : "traefik-9.18.0"
    }
    name     : "ingress-traefik"
    namespace: "ingress-traefik"
}
spec      : {
...
}
```

### Current behavior
```yaml
+ kubernetes:core/v1:Service: (create)
[urn=urn:pulumi:dev::acluster::kubernetes:helm.sh/v3:Chart$kubernetes:core/v1:Service::ingress-traefik]
[provider=urn:pulumi:dev::acluster::pulumi:providers:kubernetes::<removed>]
apiVersion: "v1"
kind      : "Service"
metadata  : {
    labels   : {
        app.kubernetes.io/instance  : "ingress-traefik"
        app.kubernetes.io/managed-by: "pulumi"
        app.kubernetes.io/name      : "traefik"
        helm.sh/chart               : "traefik-9.18.0"
    }
    name     : "ingress-traefik"
    namespace: "default"
}
spec      : {
...
}
```

## Steps to reproduce
1. Deploy Traefik using the [helm chart](https://github.com/traefik/traefik-helm-chart)

## Context (Environment)
- pulumi-kubernetes v2.8.3
- pulumi 2.23.1

## Affected feature
Helm chart deployment
