### ISSUE TITLE
Kubernetes Role.rules.apigroups[] is marked optional but actually required

### ISSUE THREAD

**Issue by codedevote** [pulumi/pulumi-kubernetes#1532]
I am using typescript to setup a k8s role and the typescript package marks k8s.rbac.v1.Role.rules.apigroups[] as optional, but when running pulumi up, I get this error:  
*creation failed: Role.rbac.authorization.k8s.io "xyz" is invalid: [rules[0].apiGroups: Required value: resource rules must supply at least one api group, rules[1].apiGroups: Required value: resource rules must supply at least one api group]*  
To add on this, I am trying to deploy to AKS.

## Expected behavior
If it's marked as optional, it should be optional. 

## Current behavior
Omitting optional parameter results in error.

## Steps to reproduce
- Have a (AKS) k8s cluster available and variable `k8sProvider` configured appropriately.
- Try to deploy a role like this: 
```yaml 
const serviceRole = new k8s.rbac.v1.Role("my-role", {
    metadata: {
        namespace: "some-namespace",
        name: "my-role"
    },
    rules: [{ 
        verbs: [ "get" ],
        resources: [ "configmaps" ],
        resourceNames: [ "name of a config map" ]
    }]
}, { provider: k8sProvider });
```

## Context (Environment)
I try to create a k8s rbac role for a service to read its related configmap but did not provide an apigroup, since api suggested the parameter is optional. After running `pulumi up` I get an error complaining an apigroup is required.

## Affected feature
-
