### ISSUE TITLE
empty strings are treated as absent values?

### ISSUE THREAD

**Issue by Iced-Sun** [pulumi/pulumi-kubernetes#1723]
I didn't find any doc about the empty string handling of optional properties, but it seems empty strings are treated as absent values ([comment](https://github.com/pulumi/pulumi-aws/issues/1046#issuecomment-661407925)). Is that true?

Anyway, with the `DefaultStorageClass` admission plugin turned on, an empty string value of `storageClassName` or an absent `storageClassName` are quite different ([ref](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1)).

Disabling the admission plugin is not feasible in our scenario.

The source:
```typescript
const pvc = new k8s.core.v1.PersistentVolumeClaim('my-pvc', {
	metadata: {
		name: 'my-pvc'
	},
	spec: {
		storageClassName: '',
		accessModes: [ 'ReadWriteOnce' ],
		resources: { requests: { storage: '10Gi' } }
	}
});
```

The output:
```
    + kubernetes:core/v1:PersistentVolumeClaim: (create)
        apiVersion: "v1"
        kind      : "PersistentVolumeClaim"
        metadata  : {
            name     : "my-pvc"
        }
        spec      : {
            accessModes     : [
                [0]: "ReadWriteOnce"
            ]
            resources       : {
                requests: {
                    storage: "10Gi"
                }
            }
        }
```

**Comment by mikhailshilkov** [comment]
Hi @Iced-Sun thank you for reporting this.

I ran the following code to export your resource to YAML:

```ts
import * as k8s from "@pulumi/kubernetes";

const yamlProvider = new k8s.Provider("yaml-provider", {
    renderYamlToDirectory: "debug-yaml",
});

const pvc = new k8s.core.v1.PersistentVolumeClaim('my-pvc', {
	metadata: {
		name: 'my-pvc'
	},
	spec: {
		storageClassName: '',
		accessModes: [ 'ReadWriteOnce' ],
		resources: { requests: { storage: '10Gi' } }
	}
}, {provider: yamlProvider});
```

and got the result:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"my-pvc"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}},"storageClassName":""}}
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: my-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
```

Similarly, I can see `storageClassName` in Pulumi state (`pulumi stack export`):

```
"urn": "urn:pulumi:dev::play-kubernetes-ts::kubernetes:core/v1:PersistentVolumeClaim::my-pvc",
"custom": true,
"id": "my-pvc",
"type": "kubernetes:core/v1:PersistentVolumeClaim",
"inputs": {
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "metadata": {
        "labels": {
            "app.kubernetes.io/managed-by": "pulumi"
        },
        "name": "my-pvc"
    },
    "spec": {
        "accessModes": [
            "ReadWriteOnce"
        ],
        "resources": {
            "requests": {
                "storage": "10Gi"
            }
        },
        "storageClassName": ""
    }
},
"outputs": {
    "apiVersion": "v1",
    "kind": "PersistentVolumeClaim",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"PersistentVolumeClaim\",\"metadata\":{\"labels\":{\"app.kubernetes.io/managed-by\":\"pulumi\"},\"name\":\"my-pvc\"},\"spec\":{\"accessModes\":[\"ReadWriteOnce\"],\"resources\":{\"requests\":{\"storage\":\"10Gi\"}},\"storageClassName\":\"\"}}\n"
        },
        "labels": {
            "app.kubernetes.io/managed-by": "pulumi"
        },
        "name": "my-pvc"
    },
    "spec": {
        "accessModes": [
            "ReadWriteOnce"
        ],
        "resources": {
            "requests": {
                "storage": "10Gi"
            }
        },
        "storageClassName": ""
    }
},
```

Could it be that the output that you show doesn't display the empty value, but it's actually applied?
