### ISSUE TITLE
Circular Dependencies, such as when using `myService.metadata.name` references

### ISSUE THREAD

**Issue by wmcnamee-tunein** [pulumi/pulumi-kubernetes#1875]
### Problem description

I’m trying to use the Kubernetes provider for Pulumi to deploy several resources, and I’m using patterns like `myService.metadata.name` in order to pass information around. I’ve found that this ends up creating dependencies, and in some cases, deadlock situations.

In my scenario, I'm using ArgoRollouts, which has a dependency on the names of several services. Services also require label selectors for pods in the Rollout.

```yaml
    # Blue-green update strategy
    blueGreen:

      # Reference to service that the rollout modifies as the active service.
      # Required.
      activeService: active-service
```

```yaml
apiVersion: v1
kind: Service
metadata:
  name: active-service
spec:
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
```

In this case, there's a clear cyclical dependency.

I do not want to _skip_ the `await`, as I could end up in a situation of deploying infrastructure that doesn't _ever_ work.

I can decouple these resources from each other by storing some information in a variable in some form, and using that variable in both places. I feel like this can lead to refactoring "gotchas", where the input value is changed in some form prior to actually assigning it to the resource, and thus, the "names" won't actually match.

Most Kubernetes resources will have static values (knowable at compile/evaluation time), and thus, it feels awkward to make a broad assumption that an await must complete before I know the value. Additionally, I don't want to skip the await, as that leads to potentially a "false negative" result (it looks successfully deployed, but isn't).

### Errors & Logs

N/A

### Affected product version(s)

```
pulumi version
v3.21.0
```

pulumi kubernetes provider `v3.14.1`

### Reproducing the issue

_TBD_

### Suggestions for a fix

I've been thinking of several different ways to handle this:

1. Marking certain fields as static vs dynamic, e.g. the `status` field would be dynamic. This would allow `static` fields to be "resolvable" before the await is complete. This is probably something that needs coordination with the Pulumi core SDK?

2. Allow the construction of Kubernetes API Objects using the native K8s SDK (e.g. https://github.com/kubernetes/api/blob/v0.23.1/apps/v1/types.go#L318), and maybe then allow a "pulumi resource" overlay of that "static" representation, by allowing `pulumi.String` (async, promise) values for fields.

In this way, I can create "static" dependencies (reference the static objects, instead of the dynamic objects)

This is somewhat similar to https://www.pulumi.com/registry/packages/kubernetes/api-docs/yaml/configgroup/ but unfortunately, this resource does not support promise-like values as inputs.
