### ISSUE TITLE
GKE: Kubernetes 1.19 or later is required to use Ingress in networking.k8s.io/v1

### ISSUE THREAD

**Issue by yellowhat** [pulumi/pulumi-kubernetes#1904]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Hi,
I am trying to deploy the `cloudbees-core` helm chart using the `3.40.1+0dc0318c25a4` version on a GKE cluster (version `1.21`):

```python
core = kubernetes.helm.v3.Release(
    "core",
    args=kubernetes.helm.v3.ReleaseArgs(
        name="cloudbees-core",
        chart="cloudbees-core",
        version="3.40.1+0dc0318c25a4",
        namespace="cloudbees-core",
        repository_opts=kubernetes.helm.v3.RepositoryOptsArgs(
            repo="https://charts.cloudbees.com/public/cloudbees",
        ),
    ),
    opts=ResourceOptions(provider=k8s_provider),
)
```
But:

```console
$ pulumi preview
Previewing update (dev):
     Type                              Name                      Plan       Info
 +   pulumi:pulumi:Stack               gcp-gke-dev               create     
 +   ├─ gcp:organizations:Project      project                   create     
 +   ├─ gcp:projects:Service           compute                   create     
 +   ├─ gcp:projects:Service           container                 create     
 +   ├─ gcp:compute:Network            vpc                       create     
 +   ├─ gcp:compute:Subnetwork         gke                       create     
 +   ├─ gcp:container:Cluster          cluster                   create     
 +   ├─ gcp:container:NodePool         pool-n2-4                 create     
 +   ├─ pulumi:providers:kubernetes    k8s                       create     
 +   ├─ kubernetes:core/v1:Namespace   core-ns                   create     
     └─ kubernetes:helm.sh/v3:Release  core                                 1 error
 
Diagnostics:
  kubernetes:helm.sh/v3:Release (core):
    error: failed to create chart from template: execution error at (cloudbees-core/templates/cjoc-ingress.yaml:2:4):
    
    ERROR: Kubernetes 1.19 or later is required to use Ingress in networking.k8s.io/v1 
```

I am not sure how to pass the kubernetes/GKE version.
`helm install ...` is working after just deploying the GKE cluster, so pulumi is not able to understand which kubernetes version will be run.

Any ideas?

Thanks

**Comment by rawkode** [comment]
@yellowhat Can you share what `k8s_provider` is set to, please?

**Comment by yellowhat** [comment]
Sure:
```python
def update_kubeconfig(args):
    """Update kubeconfig"""
    name, location, project = args
    cmd = f"""
    gcloud container clusters get-credentials \\
        {name} \\
        --zone {location} \\
        --project {project}
    """
    run(cmd, shell=True, check=True)


kubeconfig = Output.all(
    cluster.name,
    cluster.location,
    cluster.project,
).apply(update_kubeconfig)

k8s_provider = kubernetes.Provider(
    "k8s",
    opts=ResourceOptions(depends_on=[kubeconfig]),
)
```

**Comment by rawkode** [comment]
@yellowhat I don't believe this is doing what you think it's doing.

The `gcloud container clusters get-credentials` command adds the cluster information to your global `${HOME}/kube/config` file, it doesn't print or return the kubeconfig to be consumed.

This likely means that your provider that you're creating is using your current local-context, which is probably an older version of Kubernetes.

Here's an example of getting a kubeconfig for a GKE cluster:

https://github.com/pulumi/examples/blob/fe1d2864fa23ba6f9115cdfa54dc7fad0d9f59c0/gcp-py-gke/__main__.py#L43

**Comment by yellowhat** [comment]
Yes, I know that `gcloud container clusters get-credentials` writes to `${HOME}/.kube/config`, and by default `kubernetes.Provider` will look at that file.
The idea is to allow `pulumi` and `kubectl` to look at the same file.

This is an example `~/.kube/config` created by `gcloud`:
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xx
    server: https://104.196.17.14
  name: gke_us-east1-b_dev-cluster
contexts:
- context:
    cluster: gke_us-east1-b_dev-cluster
    user: gke_us-east1-b_dev-cluster
  name: gke_us-east1-b_dev-cluster
current-context: gke_us-east1-b_dev-cluster
kind: Config
preferences: {}
users:
- name: gke_us-east1-b_dev-cluster
  user:
    auth-provider:
      config:
        access-token: xxx
        cmd-args: config config-helper --format=json
        cmd-path: /usr/local/google-cloud-sdk/bin/gcloud
        expiry: "2022-02-15T11:52:00Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
It looks very similar to the one generated from [here](https://github.com/pulumi/examples/blob/fe1d2864fa23ba6f9115cdfa54dc7fad0d9f59c0/gcp-py-gke/__main__.py#L43).

Could you explain how my local-context is tailored to a older version of kubernetes?

Thanks
