### ISSUE TITLE
RFC: Kubernetes Patch Support

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#2011]
This document proposes a solution for managing shared Kubernetes (k8s) resources, also known as “patching.” Users are
welcome to respond with any comments or questions directly on this issue.

## Summary

Kubernetes resources commonly have more than one controller making changes to them. These controllers can include 
`kubectl`, the k8s control plane, custom operators, or infrastructure as code (IaC) tools like Pulumi. This presents 
particular challenges for tools that manage state independently of k8s, and need to compute diffs based on this state.

Our k8s provider currently manages resources using Client-Side Apply (CSA), which is supported by all versions of k8s. 
CSA works by including an annotation on k8s resources that encodes the last applied configuration of the resource. This 
approach has some critical limitations: 

1. CSA does not account for multiple controllers; the `last-applied-configuration` annotation is set by whichever 
   controller made the latest update 
2. Some controllers do not set the `last-applied-configuration` annotation, which can lead to other controllers 
   inadvertently reverting changes

A newer management method called [Server-Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) (SSA) is available starting in k8s v1.18 (March 2020). SSA adds a new section called `managedFields` to all k8s resources with information about which controller has set each resource field. This allows multiple controllers to independently manage the same resource without accidentally overwriting the same fields. This functionality can be used to patch and manage shared resources safely. Using SSA introduces some additional complexity to the resource lifecycle that needs to be understood and configurable by the user to avoid unexpected changes to shared resources.

## Motivation

Some cloud providers provision k8s resources as part of their managed k8s offerings. Platform teams often want to
update these default configurations, but attempting to update an existing resource will return an error in the current
Pulumi model. Resolving such a conflict currently requires a separate import step prior to making changes, and cannot
be accomplished in a single `pulumi up` operation. The following are some examples where patch behavior would be
preferable:

1. Change metadata of an existing Namespace (labels or annotations)
2. Update data in a shared ConfigMap
3. [Change configuration of a CustomResource provisioned by an external controller](https://cloud.google.com/kubernetes-engine/docs/how-to/oidc#configuring_on_a_cluster)
4. Change the number of Pod replicas in a shared Deployment
5. Ensure that a ConfigMap exists with a specified configuration
6. Ensure that a StorageClass exists with a specified configuration

## Proposal

The following changes will be made to configure the lifecycle of shared resources using Patch support.

1. SSA can be enabled by setting a Provider option. This option will be required to use Patch support. SSA support will
be disabled by default until the next major release of `pulumi-kubernetes`.
2. Each SSA-enabled Provider will set a unique manager ID per resource to enable unambiguous management of the same resource from multiple controllers. The manager ID can be set explicitly as a patchOption.
3. Each patch will be represented in Pulumi SDKs as new resource classes corresponding to each k8s resource kind. Patch
resources will be named as `<Resource>Patch`, and will live in the same namespaces as the corresponding resource. For
example, `apps.v1.Deployment` will correspond to `apps.v1.DeploymentPatch`.
4. ~The resource name will be the name of the k8s resource to patch, and will be in the form `[namespace/]name`. For
example, a ConfigMap named `app-config` in the `app-ns` namespace, will be referenced as `app-ns/app-config`.~
7. Unlike normal resource classes, every argument in a Patch resource will be optional except for `.metadata.name`. This allows users to specify only the parts of the configuration that they want to patch.
8. Patch classes will include an additional configuration argument to specify patch-specific behavior. _Edit: these options will be [specified using annotations](https://github.com/pulumi/pulumi-kubernetes/issues/2011#issuecomment-1152780251) for the initial release._
   1. `force` - boolean option to indicate that the Pulumi configuration will override any conflicting configuration for 
   shared resources; defaults to false
   2. `manager` - string option to set the name of the manager for the SSA operation; will be automatically set to a unique 
   value per resource if not provided
9. ~The `retainOnDelete` resource option will be true by default, but can be overridden by explicitly setting it to 
false. If `retainOnDelete` is false, then the shared resource will be deleted from the cluster when the stack is 
destroyed.~ When a Patch resource is destroyed, it will relinquish ownership of any fields that it manages. Any field that becomes unmanaged will reset to its default value.
10. Auto-naming isn't supported for Patch resources, so the `.metadata.name` field is required.
11. Users can explicitly [transfer ownership](https://kubernetes.io/docs/reference/using-api/server-side-apply/#transferring-ownership) of managed fields by setting the `manager` patchOption and running an update. These changes can be persisted across a `pulumi destroy` operation by setting the `retainOnDelete` option to true.
12. A new annotation, `pulumi.com/patchForce`, will be supported on existing resource classes. This annotation indicates that the provided resource definition will override existing resource configuration in case of conflict.

This pseudocode example shows how a Patch resource will be structured in each SDK.

```typescript
new k8s.core.v1.NamespacePatch(
  name="patch-example", // [required] resource name
  args={ // [required] typed resource args to patch existing resource
    metadata: {
        annotations: {
            "pulumi.com/patchForce": "true", // patch-specific arg for conflict resolution
            "pulumi.com/patchManager": "example", // patch-specific arg for field manager name
        },
        name: "kube-public", // .metadata.name is required -- all other fields are optional
    },
  }, 
  resourceOptions={ ... }, // [optional] standard resource options
);
```

## Flowcharts

The following flowcharts show the expected behavior with the SSA Provider option enabled. The normal resource classes can be used for "upsert" workflows, which will create the resource if it does not exist, or update it if it does. The Patch resource classes can be used to manage individual fields of an existing resource.

### Upsert behavior

The `pulumi.com/patchForce` annotation can be used to automatically resolve conflicts if there is an existing resource with the same name.

![upsert flowchart](https://user-images.githubusercontent.com/9253463/173140785-703e8a6b-0790-4d04-9f34-89128235f839.png)

### Patch behavior

![patch flowchart](https://user-images.githubusercontent.com/9253463/173082446-174cc069-432b-4063-a953-9359293c5581.png)

### Change metadata of an existing Namespace

```typescript
new k8s.core.v1.NamespacePatch("kube-public-patch", {
    metadata: {
        annotations: {
            team: "acmecorp",
        },
        labels: {
            foo: "bar",
        },
        name: "kube-public",
    },
});
```

```yaml
name: namespace-metadata
runtime: yaml
resources:
   kube-public-patch:
      type: kubernetes:core/v1:NamespacePatch
      properties:
         metadata:
            name: kube-public
            annotations:
               team: "acmecorp"
            labels:
               foo: bar
```

### Update data in a shared ConfigMap

```typescript
new k8s.core.v1.ConfigMapPatch("cm-patch", {
    metadata: {
        name: "app-config",
        namespace: "app-ns",
    },
    data: {
        foo: "bar",
    },
});
```

```yaml
name: configmap-data
runtime: yaml
resources:
   cm-patch:
      type: kubernetes:core/v1:ConfigMapPatch
      properties:
         metadata:
            name: app-config
            namespace: app-ns
         data:
            foo: bar
```

### Change configuration of a CustomResource provisioned by an external controller

```typescript
new k8s.apiextensions.CustomResourcePatch("oidc", {
    apiVersion: "authentication.gke.io/v2alpha1",
    kind: "ClientConfig",
    metadata: {
        name: "clientconfig",
        namespace: "kube-public",
    },
    spec: {
        authentication: {
            oidc: {
                clientID: "example",
            },
        },
    },
});
```

### Change the number of Pod replicas in a shared Deployment

```typescript
new k8s.apps.v1.DeploymentPatch("nginx-replicas", {
    metadata: {
        annotations: {
            "pulumi.com/patchForce": "true",
        },
        name: "nginx",
    },
    spec: {
        replicas: 3,
    },
});
```

```yaml
name: replicas
runtime: yaml
resources:
   nginx-replicas:
      type: kubernetes:apps/v1:DeploymentPatch
      properties:
         metadata:
            annotations:
               pulumi.com/patchForce: "true"
            name: nginx
         spec:
            replicas: 3
```

### Ensure that a ConfigMap exists with a specified configuration

```typescript
new k8s.core.v1.ConfigMap("upsert-app-config", {
   metadata: {
      annotations: {
          "pulumi.com/patchForce": "true",
      },
      name: "app-config",
      namespace: "app-ns",
   },
   data: {
      foo: "bar"
   },
});
```

```yaml
name: configmaps
runtime: yaml
resources:
   upsert-app-config:
      type: kubernetes:core/v1:ConfigMap
      properties:
         metadata:
            name: app-config
            namespace: app-ns
            annotations:
               pulumi.com/patchForce: "true"
         data:
            foo: bar
```

### Ensure that a StorageClass exists with a specified configuration

```typescript
new k8s.storage.v1.StorageClass("gp2-storage-class", {
   metadata: {
      annotations: {
         "pulumi.com/patchForce": "true",
         "storageclass.kubernetes.io/is-default-class": "true",
      },
      name: "gp2",
   },
   provisioner: "kubernetes.io/aws-ebs",
   parameters: {
      type: "gp2",
      fsType: "ext4",
   },
});
```

```yaml
name: default-storage-classes
runtime: yaml
resources:
  gp2-storage-class:
    type: kubernetes:storage.k8s.io/v1:StorageClass
    properties:
      metadata:
        name: gp2
        annotations:
          pulumi.com/patchForce: "true"
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: kubernetes.io/aws-ebs
      parameters:
        type: gp2
        fsType: ext4 
```

## Prior art

Terraform’s k8s provider has limited support for patching k8s resources, which is exposed with purpose-built resources in their SDK. They currently support patching [labels](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1616) or [annotations](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1660) on any resource, or [patching ConfigMap resources](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1671). These operations all require that the resource already exists, and was created by another controller. They support a “force” flag that works similarly to the proposed Force patch option. For deletes, they relinquish management of the specified fields, but don’t delete the resource.

By comparison, this proposal supports all resource kinds and fields. This proposal also supports an "upsert" workflow that does not require the resource to exist prior to running `pulumi up`. A combination of the upsert and patch operations give the user granular control over the intended update semantics.

## Alternatives considered

We have worked on this problem off and on since 2018, but had not reached a satisfactory answer. Previous attempts were 
based around CSA, which presents additional challenges for getting the current state of a resource, making atomic
updates to the resource, and handling conflicts with other controllers.

The [leading candidate solution](https://github.com/pulumi/pulumi-kubernetes/issues/264#issuecomment-560933184) used a combination of resource methods, `get` and `patch`, to specify the desired state. This solution had several problems that stalled progress, which were documented in [this update from January 2022](https://github.com/pulumi/pulumi-kubernetes/issues/264#issuecomment-1017833061). Additionally, this approach relies on resource methods, which are more complicated to implement cross-language, and are not currently supported in our YAML SDK.

Another alternative that was considered was doing the equivalent of `kubectl apply`, and not attempting to integrate 
this tightly with the Pulumi model. This approach would have made it difficult to preview changes and understand the 
state of the resources after the patch was applied. Like the previous solution, this was underpinned by CSA, which 
significantly complicates the implementation. It is now possible to use `kubectl apply` in the SSA mode, which would 
make this approach more viable. We previously suggested this as a workaround using the `pulumi-command` provider to 
execute the apply commands, but at the cost of poor previews and unclear delete semantics.

We initially wanted to expose Patch behavior through the existing resource classes rather than creating new resource
classes specific to Patch. However, we discovered that this approach would not be possible to implement without a
breaking change to our existing SDKs.

## Compatibility

For the initial rollout of patch support, we will allow users to opt in with a Provider feature flag. The existing
[enableDryRun](https://www.pulumi.com/registry/packages/kubernetes/api-docs/provider/#enabledryrun_nodejs) option will be deprecated in favor of a combined option that enables both Server-Side Diff and Server-Side Apply. Client-Side Apply will continue to be supported until the next major release of the k8s provider. That release will drop support for CSA and k8s versions older than v1.18.

## Related issues

* https://github.com/pulumi/pulumi-kubernetes/issues/264
* https://github.com/pulumi/pulumi-kubernetes/issues/1465
* https://github.com/pulumi/pulumi/issues/3388

**Comment by viveklak** [comment]
Thanks for the write-up @lblackstone !

> The resource name will be the name of the k8s resource to patch, and will be in the form `[namespace/]name`. For
example, a ConfigMap named app-config in the `app-ns` namespace, will be referenced as `app-ns/app-config`.

Curious why deviate from the existing naming model here for existing kubernetes resources where we use the `metadata.name/namespace`? It feels a bit restrictive to burden the pulumi resource name to be load-bearing within the context of the cluster resources. Could we just require that the `metadata.name` option instead?

**Comment by AaronFriel** [comment]
Appreciate the work that went into this!

> SSA can be enabled by setting a Provider option. This option will be required to use Patch support. SSA support will be disabled by default until the next major release of pulumi-kubernetes.

If SSA is enabled, will users be able to create-or-patch via the normal resource constructors? 

An example might be if they are deploying into a cluster that _may or may not_ contain a CRD, and they would like to create-or-update it. An example that comes to mind is [AWS EKS clusters created before 1.11 were created without storage classes](https://docs.aws.amazon.com/eks/latest/userguide/storage-classes.html) and those created after will contain them. With SSA enabled would this allow me to create-or-update the storage class?

```yaml
name: default-storage-classes
runtime: yaml
resources:
  gp2-storage-class:
    type: kubernetes:storage.k8s.io/v1:StorageClass
    properties:
      metadata:
        name: gp2
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: kubernetes.io/aws-ebs
      parameters:
        type: gp2
        fsType: ext4 
```
