### ISSUE TITLE
Unable to delete a Chart default key

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-kubernetes#2034]
### What happened?

In a Helm Chart, it's possible to delete a default key (as provided by the chart defaults) using the `null` value. On the command line, this looks like this.

```bash
helm install stable/drupal --set image=my-registry/drupal:0.1.0 --set livenessProbe.httpGet=null
```

This feature is also [documented](https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key).

However, when using this provider and the [descheduler](https://github.com/kubernetes-sigs/descheduler/tree/master/charts/descheduler) Chart, it doesn't seem to be possible to achieve the same by providing a `null`. 

Here are the details below:

In the `values.yaml` default values we find [`RemovePodsViolatingNodeAffinity`](https://github.com/kubernetes-sigs/descheduler/blob/master/charts/descheduler/values.yaml#L72-L76).

```yaml
    RemovePodsViolatingNodeAffinity:
      enabled: true
      params:
        nodeAffinityType:
        - requiredDuringSchedulingIgnoredDuringExecution
```

Of this item, we want to remove the `params` keys. In TypeScript we construct the following object for the `deschedulerPolicy` and we set `params: null`.

```
deschedulerPolicy: {
            strategies: {
              RemoveDuplicates: {
                enabled: false,
                params: null,
              },
              LowNodeUtilization: {
                enabled: false,
                params: null,
              },
              HighNodeUtilization: {
                enabled: false,
                params: null,
              },
              RemovePodsViolatingInterPodAntiAffinity: {
                enabled: false,
                params: null,
              },
              RemovePodsViolatingNodeAffinity: {
                enabled: false,
                params: null,
              },
              RemovePodsViolatingNodeTaints: {
                enabled: false,
                params: null,
              },
              RemovePodsViolatingTopologySpreadConstraint: {
                enabled: false,
                params: null,
              },
              RemovePodsHavingTooManyRestarts: {
                enabled: false,
                params: null,
              },
              PodLifeTime: {
                enabled: false,
                params: null,
              },
              RemoveFailedPods: {
                enabled: false,
                params: null,
              },
            },
          },
```
Unfortunately, the resulting configMap is like this and still contains the `params` key.

```yaml
strategies:
  HighNodeUtilization:
    enabled: false
  LowNodeUtilization:
    enabled: false
    params:
      nodeResourceUtilizationThresholds:
        targetThresholds:
          cpu: 50
          memory: 50
          pods: 50
        thresholds:
          cpu: 20
          memory: 20
          pods: 20
  PodLifeTime:
    enabled: false
  RemoveDuplicates:
    enabled: false
  RemoveFailedPods:
    enabled: false
  RemovePodsHavingTooManyRestarts:
    enabled: false
  RemovePodsViolatingInterPodAntiAffinity:
    enabled: false
  RemovePodsViolatingNodeAffinity:
    enabled: false
    params:
      nodeAffinityType:
      - requiredDuringSchedulingIgnoredDuringExecution
  RemovePodsViolatingNodeTaints:
    enabled: false
  RemovePodsViolatingTopologySpreadConstraint:
    enabled: false
```

### Steps to reproduce

To reproduce, follow these steps

1. Create a new Pulumi app for k8s
2. Create a new Helm Chart object
3. Set some keys as `null` like shown above or in the Helm documentation
4. Check the resulting deployment

### Expected Behavior

The `params` key is removed from the resulting configMap.

### Actual Behavior

The `params` key is present in the configMap.

### Versions used

➜ pulumi about
```
CLI
Version      3.34.1
Go Version   go1.17.11
Go Compiler  gc

Plugins
NAME               VERSION
kubernetes         3.19.2
internal/redacted-eks  0.0.1
nodejs             unknown

Host
OS       ubuntu
Version  20.04
Arch     x86_64

This project is written in nodejs: executable='/home/redacted/.nvm/versions/node/v16.15.0/bin/node' version='v16.15.0'

Current Stack: redacted/redacted

TYPE                                                         URN
[... some resources ...]

Found no pending operations associated with "redacted"

Backend
Name           pulumi.com
URL            https://app.pulumi.com/redacted
User           redacted
Organizations  redacted, redacted

Dependencies:
NAME                     VERSION
@pulumi/pulumi           3.33.2
@pulumi/kubernetes       3.19.2
@kubernetes/client-node  0.16.3
fast-glob                3.2.11
yaml                     2.1.1
@types/node              16.11.38

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
