### ISSUE TITLE
Upgrading an existing Helm Release results in "error: cannot re-use a name that is still in use"

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-kubernetes#2116]
### What happened?

Hi everyone,

I have the situation, where I want to upgrade an existing Helm release. This release is not deployed via Pulumi.

When I use the `helm` cli and add the flag `--reuse-values` everything works as expected.

In Pulumi, it results in error -> error: cannot re-use a name that is still in use

```yaml
 cilium:
    type: kubernetes:helm.sh/v3:Release
    properties:
      namespace: kube-system
      chart: cilium
      name: cilium
      reuseValues: true
      forceUpdate: true
      version: ${cilium-version}
      repositoryOpts:
        repo: https://helm.cilium.io/
      values:
        hubble:
          ui:
            enabled: true
          relay:
            enabled: true
    options:
      provider: ${k8s-provider}
```

Could be related to https://github.com/pulumi/pulumi-kubernetes/issues/1727

### Steps to reproduce

Create an K8s Cluster and deploy an helm chart via cli.

Try to upgrade it via Pulumi adding the `reuseValues` flag to it

### Expected Behavior

Upgrades the existing Helm Release

### Actual Behavior

error: cannot re-use a name that is still in use

### Versions used

v3.37.2

### Additional context

-

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
