### ISSUE TITLE
Pulumi hides colliding VolumeMount Paths

### ISSUE THREAD

**Issue by KaoruDev** [pulumi/pulumi-kubernetes#2201]
### What happened?

Adding a duplicate volumeMount with the same directory does not error out, instead, it gets hidden. When the directory name is updated, Pulumi (or something else) modifies the existing volume mount path instead of adding a new one breaking the volume mounts entirely.

### Steps to reproduce

1. Create Deployment

```typescript
const configMapOne = new k8s.core.v1.ConfigMap(
  "one",
  { data: { "foo.text": "foo" } }
);

const configMapTwo = new k8s.core.v1.ConfigMap(
  "two",
  { data: { "foo-2.text": "foo-2" } }
);

const testDeployment = new k8s.apps.v1.Deployment(
  "volume-mount-test",
  {
    spec: {
      selector: {
        matchLabels: { run: "volume-mount-test" },
      },
      template: {
        metadata: {
          labels: { run: "volume-mount-test" },
        },
        spec: {
          containers: [
            {
              name: "volume-mount-test",
              image: "nginx:1.14.2",
              volumeMounts: [
                {
                  name: "v1",
                  mountPath: "/opt/pulumi/volume-mount-test/v1",
                },
              ],
            },
          ],
          volumes: [
            {
              name: "v1",
              configMap: { name: configMapOne.metadata.name },
            },
          ],
        },
      },
    },
  }
);

```

2. Modify container's volumemount :

```typescript
volumeMounts: [
  {
    name: "v1",
    mountPath: "/opt/pulumi/volume-mount-test/v1",
  },
  {
    name: "v2",
    mountPath: "/opt/pulumi/volume-mount-test/v1", // note the colliding mountPath
  },
],
```

And the Deployment spec's volumes property:

```typescript
volumes: [
  {
    name: "v1",
    configMap: { name: configMapOne.metadata.name },
  },
  {
    name: "v2",
    configMap: { name: configMapTwo.metadata.name },
  },
],
```

Running `pulumi up` doesn't throw an error (which is expected since creating a deployment with colliding mountPaths throws an error).

3. See the Pod spec as:

```yaml
      volumeMounts:
      - mountPath: /opt/pulumi/volume-mount-test/v1
        name: v1
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-jq8mc
        readOnly: true
```

Telling me _something_ is ignoring the new `v2` volume mount path.

4. Modify the path of the v2 mount:

```typescript
volumeMounts: [
  {
    name: "v1",
    mountPath: "/opt/pulumi/volume-mount-test/v1",
  },
  {
    name: "v2",
    mountPath: "/opt/pulumi/volume-mount-test/v2", // Changed from v1 to v2
  },
],
```

5. Notice that the spec removes `v1` and replaces it with `v2`, even though `v1` was never removed:

```yaml
      volumeMounts:
      - mountPath: /opt/pulumi/volume-mount-test/v2
        name: v2
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-tlpg8
        readOnly: true
```

### Expected Behavior

1. Updating the v2 `mountPath` should not remove the `v1` volumeMount.
2. Adding a colliding mountPath should throw an error.

### Actual Behavior

1. When updating a deployment, colliding mountPaths does not throw an error.
2. Updating duplicate mountPaths removes other volumeMounts.

### Output of `pulumi about`

```
CLI
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME    VERSION
nodejs  unknown

Host
OS       darwin
Version  12.6
Arch     x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
