### ISSUE TITLE
Difficult (or impossible?) to create serialized YAML in a manifest

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-kubernetes#2368]
### What happened?

I'm attempting to follow [this blog post](https://jimferrari.com/2022/02/23/integrate-azure-key-vault-with-azure-kubernetes-service/) to enable Azure KeyVault as a secrets provider in an AKS cluster.

I believe I may have been exposed to the horrors of serialized YAML within YAML for the first time, that is if I'm reading this k8s manifest snippet correctly:

``` objects:  |
      array:
        - |
          objectName: demosecret # name of secret in key vault
          objectType: secret # object types: secret, key, or cert
          objectVersion: "" # defaults to latest if not specified 
```

Has anyone successfully handled this in Pulumi? If I specify it as a backticked string in TS:

```yaml
            objects: `|
                array:
                    - |
                        objectName: ${k8sSecretKey} # name of secret in key vault
                        objectType: secret # object types: secret, key, or cert
                        objectVersion:
            `,
```

I get this output if I tell the provider to spit out YAML, and this is not right:

```yaml
"|\n                array:\n                    - |\n                        objectName:
      demosecret # name of secret in key vault\n                        objectType:
      secret # object types: secret, key, or cert\n                        objectVersion:\n
      \           "
```

Is it possible to get the correct YAML output here? If so, can we document it or add a feature to the provider to make this easier, e.g. if we need a helper function in the `pulumi` namespace?

### Expected Behavior

n/a

### Steps to reproduce

See above

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by rquitales** [comment]
Interestingly, I tried to output yaml and it looks right to me:

Minimal code:
```js
const secret_provider_class_manual = new csi.secretsstore.v1.SecretProviderClass("akvprovider-demo-manual", {
    metadata: {
        name: "akvprovider-manual",
    },
    spec: {
        provider: "azure",
        parameters: {
            usePodIdentity: "false",
            keyvaultName: "mykeyvault",
            objects: `array:
  - |
    objectName: secret1
    objectType: secret
    objectVersion: ""`,
            tenantId: "mytenantid",
        },
    },
}, { provider: k8s_provider });
```

Yaml output:
```yaml
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"secrets-store.csi.x-k8s.io/v1","kind":"SecretProviderClass","metadata":{"labels":{"app.kubernetes.io/managed-by":"pulumi"},"name":"akvprovider-manual","namespace":"default"},"spec":{"parameters":{"keyvaultName":"mykeyvault","objects":"array:\n  - |\n    objectName: secret1\n    objectType: secret\n    objectVersion: \"\"","tenantId":"mytenantid","usePodIdentity":"false"},"provider":"azure"}}
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: akvprovider-manual
  namespace: default
spec:
  parameters:
    keyvaultName: mykeyvault
    objects: |-
      array:
        - |
          objectName: secret1
          objectType: secret
          objectVersion: ""
    tenantId: mytenantid
    usePodIdentity: "false"
  provider: azure
```

Note that the indentation within the backticked string is important for the output of yaml.
