### ISSUE TITLE
error when cluster is omitted when creating new provider

### ISSUE THREAD

**Issue by solomonshorser** [pulumi/pulumi-kubernetes#2376]
### What happened?

I am trying to create a new kubernetes.Provider object for an existing cluster so I can add a new namespace to it. When I pass it a cluster and kubeconfig, it works - sort-of. If I omit the cluster, I get an error. I thought that cluster was optional so I'm not sure why this happens.

The k8s cluster is in GKE.

### Expected Behavior

I expected the object to be created, whether or not he cluster was provided.

### Steps to reproduce

Code sample:

```typescript
import * as k8s from "@pulumi/kubernetes"
import * as pulumi from "@pulumi/pulumi"

// This code depends on having another pulumi stack ("my-other-stack") create the k8s cluster in gke
// and then export the kubeconfig as a pulumi output.

const otherStack = new pulumi.StackReference("my-other-stack");

const kubeConfig = otherStack.getOutput('kubeconfig')

const myCluster = new k8s.Provider("my-cluster", {
        // cluster: "gke_myProject_us-east1_my-cluster",
        kubeconfig: kubeConfig
    });

const myNamespace = new k8s.core.v1.Namespace(myNamespaceName,
        {
            metadata: {
                generateName: "false",
                name: myNamespaceName
            }
        },
        { provider: myCluster, dependsOn: myCluster }
    );
```

When I don't provide "cluster" to the Provider constructer, no plan is generated and I get this error:

<pre>
    error: failed to initialize discovery client: The gcp auth plugin has been removed.
    Please use the "gke-gcloud-auth-plugin" kubectl/client-go credential plugin instead.
    See https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke for further details
</pre>

When I provide "cluster", Pulumi provides a plan but then eventually fails when creating the namespace (other resource get created successfully):

<pre>

Diagnostics:
  kubernetes:core/v1:Namespace (my-namespace):
    error: configured Kubernetes cluster is unreachable: unable to load Kubernetes client configuration from kubeconfig file. Make sure you have:

     	 • set up the provider as per https://www.pulumi.com/registry/packages/kubernetes/installation-configuration/

     cluster "gke_myProject_us-east1_my-cluster" does not exist

</pre>

The cluster _does_ exist.

### Output of `pulumi about`

<pre>
CLI
Version      3.66.0
Go Version   go1.20.3
Go Compiler  gc

Plugins
NAME           VERSION
command        0.7.2
gcp            6.55.1
gcp            5.26.0
google-native  0.30.0
google-native  0.26.1
kubernetes     3.26.0
nodejs         unknown

Host
OS       darwin
Version  13.3.1
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v19.0.1'

Dependencies:
NAME                              VERSION
@types/node                       12.20.55
@typescript-eslint/eslint-plugin  2.34.0
@pulumi/command                   0.7.2
@pulumi/gcp                       6.55.1
@pulumi/google-native             0.30.0
@pulumi/kubernetes                3.26.0

eslint                            6.8.0
@typescript-eslint/parser         2.34.0

</pre>

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Hi @solomonshorser!

When you don't pass an explicit k8s provider object, Pulumi's k8s package will pick up the credentials from the "default context" out of `~/.kube/config` on the system you use to run Pulumi. E.g., on my system, that points to Docker Desktop's embedded Kubernetes.

You can add the "context" for any GKE cluster to the same `~/.kube/config` file using [this procedure](https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl). This context section will point to the `gke-gcloud-auth-plugin` to authenticate. But in all cases, the control plane should be reachable from system running Pulumi, either directly or via VPN.

If you don't want to add anything to your local kubernetes config file, you need to pass an explicit k8s provider object to your k8s resources, configured with the correct kubeconfig context. Still, the prerequisites on the gcloud cli tools and the `gke-gcloud-auth-plugin` still stand, as well as network connectivity. 

I hope that helps clarify things.

**Comment by solomonshorser** [comment]
That's the thing: I'm trying to use a kubeconfig that is the output of a different stack to create a provider in my new stack. This is done very deliberately to avoid having to refer to the ~/.kube/config - a few of us are working on the same project and I don't know if we all have the same local kubeconfig. Also, after initial development, the code gets run in ADO and I thought it could get cumbersome to have to create and maintain kubeconfig files.

It turns out that whoever wrote the code that created the cluster all that time ago had the foresight to export the kubeconfig as an output so it could be used in future stacks. But for some reason, I'm having some trouble.

When I relied on my local kubeconfig, I _was_ able to create k8s provider that was able to create k8s namespaces, service accounts, etc... So there is connectivity between my machine and the cluster. And I've installed gke-gcloud-auth-plugin (and set USE_GKE_GCLOUD_AUTH_PLUGIN=True) so I'm not sure why this is not working.

**Comment by solomonshorser** [comment]
Oh, I just had a thought: Maybe there's something wrong with the kubeconfig itself!

Here's the kubeconfig exported from the other stack:

```yaml
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: # some data that doesn't need to be here
        server: # the server endpooint
      name: myProject_us-east1_myCluster
    contexts:
    - context:
        cluster: myProject_us-east1_myCluster
        user: myProject_us-east1_myCluster
      name: myProject_us-east1_myCluster
    current-context: myProject_us-east1_myCluster
    kind: Config
    preferences: {}
    users:
    - name: myProject_us-east1_myCluster
      user:
        auth-provider:
          config:
            cmd-args: config config-helper --format=json
            cmd-path: gcloud
            expiry-key: '{.credential.token_expiry}'
            token-key: '{.credential.access_token}'
          name: gcp
```

I see that `cmd-path` is "gcloud". Should I find a way to change that to "gke-gcloud-auth-plugin"? Would that help?
