### ISSUE TITLE
Installing a second nginx-ingress

### ISSUE THREAD

**Issue by GhzTNFj2b19HRNAJBDKSGFYqIctv4** [pulumi/pulumi-kubernetes#2500]
### What happened?

I'm trying to install a second nginx-ingress with below pulumi.yaml

```
  nginx-ingress-vpn:
    type: kubernetes:helm.sh/v3:Release
    properties: # The arguments to resource properties.
      chart: "ingress-nginx"
      repositoryOpts:
        repo: https://kubernetes.github.io/ingress-nginx
      cleanupOnFail: true
      lint: true
      name: "nginx-ingress-vpn"
      namespace: "nginx-ingress-vpn"
      version: "4.7.1"
      values:
        controller.ingressClassResource.name: "nginx-ingress-vpn"
        controller.ingressClassResource.enabled: true
        controller.ingressClassResource.controllerValue: "k8s.io/nginx-ingress-vpn"
        controller.ingressClass: "nginx-ingress-vpn"
        controller.annotations: "meta.helm.sh/release-namespace=nginx-ingress-vpn"

```

The error is:

```
@ updating....
 +  kubernetes:helm.sh/v3:Release nginx-ingress-vpn creating (8s) error: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "nginx-ingress-vpn": current value is "ingress-nginx"
 +  kubernetes:helm.sh/v3:Release nginx-ingress-vpn **creating failed** error: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "nginx-ingress-vpn": current value is "ingress-nginx"
@ updating....
    pulumi:pulumi:Stack boom-[MASKED] running error: update failed
    pulumi:pulumi:Stack boom-[MASKED] **failed** 1 error
Diagnostics:
  pulumi:pulumi:Stack (boom-[MASKED]):
    error: update failed
  kubernetes:helm.sh/v3:Release (nginx-ingress-vpn):
    error: rendered manifests contain a resource that already exists. Unable to continue with install: IngressClass "nginx" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "nginx-ingress-vpn": current value is "ingress-nginx"
Resources:
    12 unchanged
Duration: 16s
```

I can install a second nginx-ingress with below helm command:

```
helm install nginx-ingress-vpn ingress-nginx/ingress-nginx -n ingress-nginx \
  --set controller.ingressClass=nginx-ingress-vpn \
  --set controller.ingressClassResource.name=nginx-ingress-vpn \
  --set controller.ingressClassResource.controllerValue=k8s.io/nginx-ingress-vpn \
  --set spec.ingressClassName=nginx-ingress-vpn \
  --debug
```

After removing the helm release and trying to install again with Pulumi I get the same error as above.

```
helm ls -A
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-nginx           ingress-nginx   2               2023-07-17 11:37:20.140681416 +0000 UTC deployed        ingress-nginx-4.7.1     1.8.1      
```

```
kubectl get IngressClass -A
NAME    CONTROLLER             PARAMETERS   AGE
nginx   k8s.io/ingress-nginx   <none>       4d1h

kubectl get IngressClass nginx -o yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
  creationTimestamp: "2023-07-13T10:46:06Z"
  generation: 1
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.8.1
    helm.sh/chart: ingress-nginx-4.7.1
  name: nginx
  resourceVersion: "11949294"
  uid: dff93170-b986-42cc-a73d-66634bba2692
spec:
  controller: k8s.io/ingress-nginx
```

The first nginx-ingress is installed using below pulumi.yaml

```  nginx-ingress:
    type: kubernetes:helm.sh/v3:Release
    properties: # The arguments to resource properties.
      chart: "ingress-nginx"
      repositoryOpts:
        repo: https://kubernetes.github.io/ingress-nginx
      cleanupOnFail: true
      lint: true
      name: "ingress-nginx"
      namespace: "ingress-nginx"
      version: "4.7.1"
```

I already tried changing the namespace but I get the same error.

### Expected Behavior

Pulumi should install nginx-ingress with a different IngressClass in another namespace.

### Steps to reproduce

Run pulumi with below pulumi.yaml

```
  #
  # Deploy nginx ingress controller
  #
  nginx-ingress:
    type: kubernetes:helm.sh/v3:Release
    properties: # The arguments to resource properties.
      chart: "ingress-nginx"
      repositoryOpts:
        repo: https://kubernetes.github.io/ingress-nginx
      cleanupOnFail: true
      lint: true
      name: "ingress-nginx"
      namespace: "ingress-nginx"
      version: "4.7.1"

  #
  # Deploy nginx ingress controller restricted to VPNd
  #
  nginx-ingress-vpn:
    type: kubernetes:helm.sh/v3:Release
    properties: # The arguments to resource properties.
      chart: "ingress-nginx"
      repositoryOpts:
        repo: https://kubernetes.github.io/ingress-nginx
      cleanupOnFail: true
      lint: true
      name: "nginx-ingress-vpn"
      namespace: "nginx-ingress-vpn"
      version: "4.7.1"
      values:
        controller.ingressClassResource.name: "nginx-ingress-vpn"
        controller.ingressClassResource.enabled: true
        controller.ingressClassResource.controllerValue: "k8s.io/nginx-ingress-vpn"
        controller.ingressClass: "nginx-ingress-vpn"
        controller.annotations: "meta.helm.sh/release-namespace=nginx-ingress-vpn"
```

### Output of `pulumi about`

```
pulumi about
CLI          
Version      3.73.0
Go Version   go1.20.5
Go Compiler  gc
Plugins
NAME        VERSION
gcp         unknown
kubernetes  unknown
yaml        unknown
Host     
OS       debian
Version  11.7
Arch     x86_64
This project is written in yaml
Current Stack: organization/boom/[MASKED]
TYPE                                URN
pulumi:pulumi:Stack                 urn:pulumi:[MASKED]::boom::pulumi:pulumi:Stack::boom-[MASKED]
pulumi:providers:gcp                urn:pulumi:[MASKED]::boom::pulumi:providers:gcp::default
gcp:serviceAccount/account:Account  urn:pulumi:[MASKED]::boom::gcp:serviceAccount/account:Account::gke-sa
gcp:compute/network:Network         urn:pulumi:[MASKED]::boom::gcp:compute/network:Network::gke-vpc
pulumi:providers:kubernetes         urn:pulumi:[MASKED]::boom::pulumi:providers:kubernetes::default
kubernetes:helm.sh/v3:Release       urn:pulumi:[MASKED]::boom::kubernetes:helm.sh/v3:Release::nginx-ingress
gcp:compute/subnetwork:Subnetwork   urn:pulumi:[MASKED]::boom::gcp:compute/subnetwork:Subnetwork::gke-primary-range-pods
gcp:compute/subnetwork:Subnetwork   urn:pulumi:[MASKED]::boom::gcp:compute/subnetwork:Subnetwork::gke-primary-range-services
gcp:compute/subnetwork:Subnetwork   urn:pulumi:[MASKED]::boom::gcp:compute/subnetwork:Subnetwork::gke-primary-range-nodes
gcp:container/cluster:Cluster       urn:pulumi:[MASKED]::boom::gcp:container/cluster:Cluster::gke
gcp:serviceAccount/account:Account  urn:pulumi:[MASKED]::boom::gcp:serviceAccount/account:Account::gke-sa
gcp:container/nodePool:NodePool     urn:pulumi:[MASKED]::boom::gcp:container/nodePool:NodePool::gke-nodes
Found no pending operations associated with [MASKED]
Backend        
Name           runner-xxxxx-xxxxx-xxxxx-concurrent-xxxxx
URL            gs://xxxxx
User           root
Organizations  
No dependencies found
Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by thomas11** [comment]
Thank you for reporting this, @GhzTNFj2b19HRNAJBDKSGFYqIctv4! We'll look into it as soon as we can.

**Comment by GhzTNFj2b19HRNAJBDKSGFYqIctv4** [comment]
Hi,
I began with a clean slate, erasing everything in Google Cloud, which includes both the stack and the pulumi state file.
I then deployed the following:

- vpc
- gke
- nodes
- I deployed both below using kubernetes:helm.sh/v3:Release
- rayoperator
- rayapiserver


After ensuring everything was working fine, I proceeded to add two `kubernetes:helm.sh/v3:Release` configurations for two nginx installations:

- ingress-nginx
- ingress-nginx-vpn

**Configuration Details:**
```
ingress-nginx:
    type: kubernetes:helm.sh/v3:Release
    properties: # The arguments to resource properties.
      chart: "ingress-nginx"
      repositoryOpts:
        repo: https://kubernetes.github.io/ingress-nginx
      cleanupOnFail: true
      createNamespace: true
      lint: true
      name: "ingress-nginx"
      namespace: "ingress-nginx"
      version: "4.7.1"
      values:
        ingressClassResource:
          name: "internet"
          enabled: true
          controllerValue: "k8s.io/internet"
        ingressClass: "internet"
        annotations: "meta.helm.sh/release-namespace=ingress-nginx"
    options:
      provider: ${provider}
      dependsOn:
      - ${gke-cluster-native}
      - ${gke-cluster-vpc}
      parent: ${gke-cluster-native}

  #
  # Deploy nginx ingress controller for VPN access
  #  
  ingress-nginx-vpn:
    type: kubernetes:helm.sh/v3:Release
    properties: # The arguments to resource properties.
      chart: "ingress-nginx"
      repositoryOpts:
        repo: https://kubernetes.github.io/ingress-nginx
      cleanupOnFail: true
      createNamespace: true
      lint: true
      name: "ingress-nginx-vpn"
      namespace: "ingress-nginx-vpn"
      version: "4.7.1"
      values:
        ingressClassResource:
          name: "vpn"
          enabled: true
          controllerValue: "k8s.io/vpn"
        ingressClass: "vpn"
        annotations: "meta.helm.sh/release-namespace=ingress-nginx-vpn"
    options:
      provider: ${provider}
      dependsOn:
      - ${gke-cluster-native}
      - ${gke-cluster-vpc}
      parent: ${gke-cluster-native}
```

**Gitlab job log:**

Notably, there was a warning indicating a new version of Pulumi, suggesting an upgrade from 3.77.1 to 3.78.1.

```
Getting source from Git repository
Executing "step_script" stage of the job script
Activated service account credentials for: [REDACTED-@[MASKED].iam..com]
warning: A new version of Pulumi is available. To upgrade from version '3.77.1' to '3.78.1', visit https://pulumi.com/docs/install/ for manual instructions and release notes.
$ pulumi stack select $STACK
$ pulumi config set google-native:project ${REDACTED_RND_GCP_PROJECT}
$ pulumi config set gcp:project ${REDACTED_RND_GCP_PROJECT}
$ pulumi config set gcp:region ${REDACTED_RND_GCP_REGION}
$ pulumi update --yes
Previewing update ([MASKED]):
[resource plugin google-native-0.31.1] installing
@ previewing update....[resource plugin kubernetes-4.0.3] installing
[resource plugin gcp-6.62.0] installing
.
    pulumi:pulumi:Stack REDACTED-[MASKED] running 
@ previewing update....
.
    gcp:serviceAccount:Account gke-cluster-sa  
    gcp:compute:Network gke-cluster-vpc  
    gcp:compute:Subnetwork gke-cluster-primary-range-nodes  
    gcp:compute:Subnetwork gke-cluster-primary-range-services  
    gcp:compute:Subnetwork gke-cluster-primary-range-pods  
    google-native:container/v1beta1:Cluster gke-cluster-native  
    gcp:serviceAccount:Account gke-cluster-nodepool-sa  
    pulumi:providers:kubernetes provider  
    gcp:container:NodePool gke-[MASKED]-a  
    gcp:container:NodePool ray-2-[MASKED]-c  
@ previewing update....
.
kubernetes:helm.sh/v3:Release kuberay-operator  
@ previewing update....
.
 +  kubernetes:helm.sh/v3:Release ingress-nginx create 
@ previewing update....
.
 +  kubernetes:helm.sh/v3:Release ingress-nginx-vpn create 
@ previewing update....
.
kubernetes:helm.sh/v3:Release kuberay-apiserver  
pulumi:pulumi:Stack REDACTED-[MASKED]  
Resources:
    + 2 to create
    13 unchanged
Updating ([MASKED]):
pulumi:pulumi:Stack REDACTED-[MASKED] running 
@ updating....
.
    gcp:serviceAccount:Account gke-cluster-sa  
    gcp:compute:Network gke-cluster-vpc  
    gcp:compute:Subnetwork gke-cluster-primary-range-pods  
    gcp:compute:Subnetwork gke-cluster-primary-range-nodes  
    gcp:compute:Subnetwork gke-cluster-primary-range-services  
@ updating....
    google-native:container/v1beta1:Cluster gke-cluster-native  
    gcp:serviceAccount:Account gke-cluster-nodepool-sa  
    pulumi:providers:kubernetes provider  
    gcp:container:NodePool gke-[MASKED]-a  
    gcp:container:NodePool ray-2-[MASKED]-c  
@ updating....
.
.
    kubernetes:helm.sh/v3:Release kuberay-operator  
@ updating....
.
 +  kubernetes:helm.sh/v3:Release ingress-nginx-vpn creating (0s) 
@ updating....
.
 +  kubernetes:helm.sh/v3:Release ingress-nginx creating (0s) 
@ updating....
.
    kubernetes:helm.sh/v3:Release kuberay-apiserver  
@ updating....
.
 +  kubernetes:helm.sh/v3:Release ingress-nginx creating (28s) warning: Helm release "ingress-nginx" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then retry. Reason: 1 error occurred:
 +  kubernetes:helm.sh/v3:Release ingress-nginx creating (28s) error: 1 error occurred:
 +  kubernetes:helm.sh/v3:Release ingress-nginx **creating failed** error: 1 error occurred:
@ updating....
.
 +  kubernetes:helm.sh/v3:Release ingress-nginx-vpn created (84s) 
@ updating....
.
.
    pulumi:pulumi:Stack REDACTED-[MASKED] running error: update failed
    pulumi:pulumi:Stack REDACTED-[MASKED] **failed** 1 error
Diagnostics:
  kubernetes:helm.sh/v3:Release (ingress-nginx):
    warning: Helm release "ingress-nginx" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then retry. Reason: 1 error occurred:
        * ingressclasses.networking.k8s.io "nginx" already exists
    error: 1 error occurred:
        * Helm release "ingress-nginx/ingress-nginx" was created, but failed to initialize completely. Use Helm CLI to investigate.: failed to become available within allocated timeout. Error: Helm Release ingress-nginx/ingress-nginx: 1 error occurred:
        * ingressclasses.networking.k8s.io "nginx" already exists
  pulumi:pulumi:Stack (REDACTED-[MASKED]):
    error: update failed
Resources:
    + 1 created
    13 unchanged
Duration: 1m36s
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1
```

**Helm:**
```
helm ls -A
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-nginx           ingress-nginx           1               2023-08-14 10:25:10.346141657 +0000 UTC failed          ingress-nginx-4.7.1     1.8.1      
ingress-nginx-vpn       ingress-nginx-vpn       1               2023-08-14 10:25:10.309215065 +0000 UTC deployed        ingress-nginx-4.7.1     1.8.1      
kuberay-apiserver       ray-system              1               2023-08-10 16:28:36.23350083 +0000 UTC  deployed        kuberay-apiserver-0.5.0            
kuberay-operator        ray-system              1               2023-08-10 16:22:35.348352147 +0000 UTC deployed        kuberay-operator-0.5.0             
```

**Pods:**
```
kubectl get pods -A | grep nginx
ingress-nginx-vpn   ingress-nginx-vpn-controller-6674596c84-2xc6c                    1/1     Running   0               22m
ingress-nginx       ingress-nginx-controller-5fcb5746fc-vr89d                        1/1     Running   0               22m
```

Interestingly, despite the helm ingress-nginx deployment failing, the corresponding pods are operating as expected.

Separate note: Attempting to delete either nginx or the entire cluster presents issues due to this helm failure. For an effective stack destruction, Pulumi should prioritize deleting helm. If Pulumi deletes the GKE cluster prior to addressing helm, it could encounter errors because it won't recognize the helm release on a non-existent GKE.

When i run the update again, it fixed the failed helm deployment 🤷‍♀️ 

```
helm ls -A
NAME                    NAMESPACE               REVISION        UPDATED                                 STATUS          CHART                   APP VERSION
ingress-nginx           ingress-nginx           2               2023-08-14 12:17:44.146742142 +0000 UTC deployed        ingress-nginx-4.7.1     1.8.1      
ingress-nginx-vpn       ingress-nginx-vpn       1               2023-08-14 10:25:10.309215065 +0000 UTC deployed        ingress-nginx-4.7.1     1.8.1      
kuberay-apiserver       ray-system              1               2023-08-10 16:28:36.23350083 +0000 UTC  deployed        kuberay-apiserver-0.5.0            
kuberay-operator        ray-system              1               2023-08-10 16:22:35.348352147 +0000 UTC deployed        kuberay-operator-0.5.0
```
