### ISSUE TITLE
Helm Release triggering an unexpected diff when updating from 4.4.0 to 4.5.1 or later and resulting in unexpected behavior

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-kubernetes#2652]
### What happened?

When updating from `4.4.0` to `4.5.1` I get a diff on the checksum and resourceNames with an unexpected value from a helm evaluation based on the kube version. Also, after running a pulumi up accepting the diff, it doesn't actually make any changes and behaves as one would expect had there been no diff.

The relevant conditional in the heml yaml is
```yaml
{{ if semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: apps/v1
{{ else }}
apiVersion: apps/v1beta1
{{ end }}
```
The cluster I am using is `version 1.24` and the diff that it displays is as follows. Notice the v1beta1
```
      ~ resourceNames: {
          - Deployment.apps/apps/v1     : [
          -     [0]: "my-basic-deployment"
            ]
          + Deployment.apps/apps/v1beta1: [
          +     [0]: "my-basic-deployment"
            ]
        }
```

## Typescript Code
```ts
const alb = new k8s.helm.v3.Release("test-manifest", {
    chart: "./testChart",
    namespace: 'default',
    skipAwait: false,
    values: {
        clusterName: cluster.eksCluster.name
    }
}, { 
    dependsOn: [cluster],
    provider: k8sProvider
});
```
## Helm Yaml inside TestChart
```yaml
{{ if semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: apps/v1
{{ else }}
apiVersion: apps/v1beta1
{{ end }}
kind: Deployment
metadata:
  name: my-basic-deployment
  labels:
    app: my-basic-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-basic-app
  template:
    metadata:
      labels:
        app: my-basic-app
        helmVersionGreaterThan21:  {{- if semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version }} "greaterOrEqualTo-1.21.0" {{- else }} "below-1.21.0" {{- end }}  #Evaluates to greaterOrEqualTo-1.21.0
        helmVersionEval: {{.Capabilities.KubeVersion.Version}} #Evaluates to v1.24.17-eks-4f4795d
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

### Output of `pulumi about`

```
CLI          
Version      3.90.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.7.0
aws         5.31.0
awsx        2.1.1
docker      4.4.4
docker      3.6.1
eks         1.0.4
kubernetes  4.5.1
kubernetes  3.30.2
nodejs      unknown

Host     
OS       darwin
Version  14.0
Arch     arm64
```

### Additional context

The output of `Deployment.apps/apps/v1beta1` is unexpected as the version evaluates correctly in the rest of the code to 1.24 based on some duplicate conditionals I have set. The conditional in the yaml should not be resulting in a value of `Deployment.apps/apps/v1beta1` As a test, strangely if I change the code to the following
```yaml
{{ if semverCompare ">=1.21.0-0" .Capabilities.KubeVersion.Version }}
apiVersion: apps/v1
{{ else }}
apiVersion: {{.Capabilities.KubeVersion.Version}}
{{ end }}
```
The diff is evaluating .Capabilities.KubeVersion.Version to be v1.20.0 as seen below 
```
  ~ albDetails: {
      - Deployment.apps/apps/v1: [
      -     [0]: "my-basic-deployment"
        ]
      + Deployment/v1.20.0     : [
      +     [0]: "my-basic-deployment"
        ]
    }
```
This again, doesn't actually result in any real changes on the cloud provider and in the state it will show the input of the unexpected value, but the outputs reflect the correct values. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
