### ISSUE TITLE
Ingress without load balancer never completes

### ISSUE THREAD

**Issue by jam13** [pulumi/pulumi-kubernetes#268]
I am using Traefik for handling k8s ingress. which creates resources like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: myingress
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: foo
          servicePort: http
        path: /
status:
  loadBalancer: {}
```

The ingress is being created successfully using the helm method, however pulumi never completes as it seems to be awaiting a load balancer status that will never appear.

https://github.com/pulumi/pulumi-kubernetes/blob/2efb314c64218897bb88895bc468e7c231c8ee88/pkg/await/awaiters.go#L542-L554

I there any workaround for this kind of situtation?
