### ISSUE TITLE
Unable to create Provider with correct Kubeconfig

### ISSUE THREAD

**Issue by blaargh** [pulumi/pulumi-kubernetes#2712]
### What happened?

When trying to use NewProvider with a kubeconfig from file, it is unable to parse the yaml:

> failed to parse kubeconfig: yaml: line 4: found character that cannot start any token

The Yaml file is valid and kubectl from the console can be executed without issues using this kubeconfig

### Example

```
// load kubeconfig from file
content, err := os.ReadFile("/path/to/kubeconfig.yaml")
if err != nil {
    log.Panic(err)
}
kubeconfig := string(content)
// Create new provider from config
k8sProvider, err := kubernetes.NewProvider(ctx, "k8sprovider", &kubernetes.ProviderArgs{
		Kubeconfig: pulumi.String(kubeconfig),
	})
```

Kubeconfig looks like this (sensitive information redacted):

```
apiVersion: v1
clusters:
- cluster:
    server: <redacted>
    certificate-authority-data: <redacted>
  name: <redacted>
contexts:
- context:
    cluster: <redacted>
    user: <redacted>
  name: internal
current-context: internal
kind: Config
preferences: {}
users:
- name: <redacted>
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - --region
      - <redacted>
      - eks
      - get-token
      - --cluster-name
      - "internal"
      env:
      - name: AWS_PROFILE
        value: internal
```

### Output of `pulumi about`

CLI          
Version      3.96.2
Go Version   go1.21.5
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.0.2
go          unknown
kubernetes  4.5.5
kubernetes  3.30.2
kubernetes  1.6.0

Host     
OS       darwin
Version  14.2
Arch     arm64

This project is written in go: executable='/usr/local/go/bin/go' version='go version go1.21.5 darwin/arm64'

Dependencies:
NAME                                        VERSION
github.com/pulumi/pulumi-aws/sdk/v6         6.0.2
github.com/pulumi/pulumi/sdk/v3             3.92.0
gopkg.in/yaml.v2                            2.4.0
github.com/pulumi/pulumi-kubernetes         1.6.0
github.com/pulumi/pulumi-kubernetes/sdk/v3  3.30.2
github.com/pulumi/pulumi-kubernetes/sdk/v4  4.5.5

### Additional context

Reverting back to pulumi version 3.91.1 fixes this issue.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
