### ISSUE TITLE
yaml/v2: Detect file patterns automatically

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes#2871]
There's an asymmetrical experience in `ConfigGroup` vs `ConfigFile` when it comes to the handling of non-existent files. `ConfigFile` produces an error, whereas `ConfigGroup` doesn't because the latter interprets all paths as patterns. For example, consider this program:

```yaml
resources:
  cf:
    type: kubernetes:yaml/v2:ConfigFile
    properties:
      file: ./manifest.yaml
  cg:
    type: kubernetes:yaml/v2:ConfigGroup
    properties:
      files:
        - ./manifest.yaml
```

I feel that the behavior of the two resources should be consistent when `manifest.yaml` is non-existent, but in actuality the `ConfigGroup` would silently produce no children, which the program author probably didn't intend.

My proposal is to detect whether a given file entry is a pattern, by looking for the characters ‘*’, ‘?’, and ‘[’ as is done in [Bash filename expansion](https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html).
