### ISSUE TITLE
k8s client tuning settings are ignored

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes#2981]
### What happened?

I tuned the client settings on my provider, but the settings don't seem to take effect. 

### Example

```yaml
name: example
runtime: yaml
resources:
  provider:
    type: pulumi:providers:kubernetes
    properties:
      kubeClientSettings:
        burst: 500
        qps: 1
        timeout: 5
```

### Output of `pulumi about`

```
CLI          
Version      3.113.3
Go Version   go1.22.2
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  kubernetes  unknown
resource  random      unknown
language  yaml        unknown

Host     
OS       darwin
Version  14.4.1
Arch     arm64
```

### Additional context

I believe the issue is due to a regression caused by: https://github.com/pulumi/pulumi-kubernetes/pull/1748

The logic should be:
```go
	if burst := os.Getenv("PULUMI_K8S_CLIENT_BURST"); burst != "" && kubeClientSettings.Burst == nil {
		asInt, err := strconv.Atoi(burst)
		if err != nil {
			return nil, fmt.Errorf("invalid value specified for PULUMI_K8S_CLIENT_BURST: %w", err)
		}
		kubeClientSettings.Burst = &asInt
	} else if kubeClientSettings.Burst == nil {
		v := 120 // Increased from default value of 10
		kubeClientSettings.Burst = &v
	}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
