### ISSUE TITLE
helm.v4.Chart: failed to install a helm chart that depends on another helm chart CRD

### ISSUE THREAD

**Issue by kirgene** [pulumi/pulumi-kubernetes#3035]
### What happened?

I'm installing two helm charts:
* [external-secrets](https://github.com/external-secrets/external-secrets)
* `secrets`: a custom helm chart that creates `ExternalSecret` resources.

The `secrets` helm chart depends on the `external-secrets`
When I run `pulumi up` I'm getting the following error:
```
ensure CRDs are installed first, resource mapping not found for name: "repo-secret" namespace: "argo-cd" from "": no matches for kind "ExternalSecret" in version "external-secrets.io/v1beta1"
```

where `repo-secret` is the resources provided by the `secrets` helm chart

### Example

```
from pulumi_kubernetes.helm.v4 import Chart, ChartArgs, RepositoryOptsArgs

ext_secrets = Chart(
        'external-secrets',
        ChartArgs(
            chart='external-secrets',
            version='0.9.11',
            namespace='external-secret',
            repository_opts=RepositoryOptsArgs(repo='https://charts.external-secrets.io'),
        ),
    )

secrets = Chart(
        'secrets',
        ChartArgs(
            chart='oci://..../secrets',
            version='0.2.0',
            namespace='argo-cd',
        ),
        opts=ResourceOptions.merge(opts, ResourceOptions(depends_on=ext_secrets)),
    )

```

### Output of `pulumi about`

```
CLI
Version 3.117.0
Go Version go1.22.3
Go Compiler gc

Plugins
KIND NAME VERSION
resource kubernetes 4.12.0
language python unknown
resource tls 5.0.3

Host
OS ubuntu
Version 22.04
Arch x86_64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
I see the CRDs get created when I install the external-secrets chart locally, and the `depends_on` relationship _should_ do the trick.

@kirgene do you see this error during `preview` as well as during `up --skip-preview`?

What happens if you install only the `ext_secrets` chart with Pulumi (so remove the `secrets` chart) and then manually install the other chart using the `helm` CLI? Something like this:

```
helm install secrets oci://..../secrets --no-hooks --version 0.2.0 --namespace argo-cd
```

Does that work or do you see the same error?

**Comment by kirgene** [comment]
The issues happen during the preview. I haven't tested without a preview.
Everything works fine with **helm.v3.Chart**

**Comment by EronWright** [comment]
This is fixed in pulumi-kubernetes v4.13. The root cause was a unnecessary Helm validation step, is fixed in https://github.com/pulumi/pulumi-kubernetes/pull/3046

@kirgene be sure to use the `depends_on` option to ensure that the first chart is installed before the second chart.  Here's my repro script, to demonstrate:

```yaml
name: issue-3035
runtime: yaml
description: A demonstration of installing a CRD in one chart and then using it in another chart.
resources:
  ns:
    type: kubernetes:core/v1:Namespace
    properties:
      metadata:
        name: external-secrets

  external-secrets:
    type: kubernetes:helm.sh/v4:Chart
    properties:
      namespace: ${ns.metadata.name}
      chart: external-secrets
      version: "0.9.11"
      repositoryOpts:
        repo: https://charts.external-secrets.io

  secrets:
    type: kubernetes:helm.sh/v4:Chart
    properties:
      namespace: ${ns.metadata.name}
      chart: ./charts/secrets
    options:
      dependsOn:
      - ${external-secrets}
```
