### ISSUE TITLE
Chart v4 fails on update

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes#3045]
### What happened?

I tried to use `Chart` v4 to install cert-manager and saw an unexpected error during a subsequent update.

```
error: an unhandled error occurred: waiting for RPCs: rpc error: code = Unknown desc = Unable to continue with install: NetworkPolicy "certman-oci" in namespace "cert-manager" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "certman-oci"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "cert-manager"
```

### Example

```yaml
name: example
runtime: yaml
resources:
  certman-ns:
    type: kubernetes:core/v1:Namespace
    properties:
      metadata:
        name: cert-manager
  certman-oci:
    type: kubernetes:helm.sh/v4:Chart
    properties:
      namespace: ${certman-ns.metadata.name}
      chart: oci://registry-1.docker.io/bitnamicharts/cert-manager
      version: "1.1.0"
```

### Output of `pulumi about`

```
CLI          
Version      3.117.0
Go Version   go1.22.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  kubernetes  unknown
language  yaml        unknown

Host     
OS       darwin
Version  14.4.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
