### ISSUE TITLE
How to ensure compatibility with manual helm in helm mode

### ISSUE THREAD

**Issue by novohool** [pulumi/pulumi-kubernetes#3255]
helm code:
>file: pkg/action/validate.go
```
func mergeAnnotations(obj runtime.Object, annotations map[string]string) error {
	current, err := accessor.Annotations(obj)
	if err != nil {
		return err
	}
	return accessor.SetAnnotations(obj, mergeStrStrMaps(current, annotations))
}

		if err := mergeAnnotations(info.Object, map[string]string{
			helmReleaseNameAnnotation:      releaseName,
			helmReleaseNamespaceAnnotation: releaseNamespace,
		}); err != nil {
			return fmt.Errorf(
				"%s annotations could not be updated: %s",
				resourceString(info), err,
			)
		}
```
pulumi helm need
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: app
    meta.helm.sh/release-namespace: default

```
