### ISSUE TITLE
Built-in await logic for PKO Stack resources

### ISSUE THREAD

**Issue by EronWright** [pulumi/pulumi-kubernetes#3318]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

When one uses Pulumi to create a `pulumi.com/v1/Stack` resource, the provider should automatically wait for the Ready condition.  Otherwise a user must specify the annotation manually:

```yaml
kind: Stack
metadata:
  annotations:
    pulumi.com/waitFor: "condition=Ready"
```
