### ISSUE TITLE
"YAML object does not have a .metadata.name" error when use the ConfigGroup with a generated name

### ISSUE THREAD

**Issue by emirozmen07** [pulumi/pulumi-kubernetes#3370]
### What happened?

I was trying to use the `ConfigGroup` to release a number of `YAML` job files and some of the files does not have a name in their `metadata`, instead they have `generateName` property. But when you run the `ConfigGroup` class with this file it does not recognize this name and returns the error below.

```
 Exception: YAML object does not have a .metadata.name: batch/v1/Job 
```

### Example

```
        self.k8s_provider = k8s.Provider(pulumi.get_stack())
        k8s_resources = k8s.yaml.ConfigGroup(
            self.name,
            files=self.yaml_files,
            opts=pulumi.ResourceOptions(provider=self.k8s_provider),
        )
```

Try to insert the YAML below using the code above.

```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: project-backup-
  namespace: current_namespace
  labels:
    app: project-backup
spec:
  ttlSecondsAfterFinished: 54000
  template:
    metadata:
      name: project-backup
    spec:
      containers:
        - name: backup-engine
          image: europe-west1-docker.pkg.dev/test_name/test_name-docker-repo/backup-project:latest
      restartPolicy: Never
      imagePullSecrets:
        - name: docker-registry-company
```

### Output of `pulumi about`

```
CLI          
Version      3.139.0
Go Version   go1.23.3
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  docker      4.5.5
resource  gcp         7.38.0
resource  kubernetes  4.17.1
resource  postgresql  3.11.3
language  python      3.139.0
resource  random      4.16.4

Host     
OS       darwin
Version  14.5
Arch     x86_64


Dependencies:
NAME              VERSION
pip               24.2
pulumi_random     4.16.4
setuptools        74.1.2
wheel             0.44.0

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
