### ISSUE TITLE
Ingress await logic doesn't handle ssl-redirect case for aws-alb-ingress-controller

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#408]
https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:xxxx:certificate/xxxxxx
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  rules:
    - http:
        paths:
         - path: /*
           backend:
             serviceName: ssl-redirect
             servicePort: use-annotation
```
produces an error similar to
```
kubernetes:extensions:Ingress  core-django               creating...  No matching service found for ingress rule: "***-staging.***.com/*" -> "ssl-redirect"
```

Reported at: https://pulumi-community.slack.com/archives/C84L4E3N1/p1549491112121100
