### ISSUE TITLE
Error parsing unquoted timestamp in ConfigGroup

### ISSUE THREAD

**Issue by hazsetata** [pulumi/pulumi-kubernetes#501]
Trying to add a YAML file as ConfigGroup like this:

```typescript
let linkerdCG = new k8s.yaml.ConfigGroup("linkerd-cg",
    {
        files: "t.yaml",
    },
    {
        providers: {
            kubernetes: kubernetesCluster.kubernetesProvider
        },
        dependsOn: [ kubernetesCluster.kubernetesProvider ]
    }
);
```

with `t.yaml`'s content being:

```yaml
---
kind: Namespace
apiVersion: v1
metadata:
  name: linkerd
  annotations:
    linkerd.io/inject: disabled
---
kind: Secret
apiVersion: v1
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
  labels:
    linkerd.io/control-plane-component: identity
  annotations:
    linkerd.io/created-by: linkerd/cli edge-19.3.3
    linkerd.io/identity-issuer-expiry: 2020-03-25T13:37:11Z
data:
  crt.pem: ZXhhbXBsZQ==
  key.pem: dmFsdWU=
```

results in an error:

```
error: Plan apply failed: Secret in version "v1" cannot be handled as a Secret: v1.Secret.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found {, error found in #10 byte of ...|-expiry":{}},"labels|..., bigger context ...|edge-19.3.3","linkerd.io/identity-issuer-expiry":{}},"labels":{"app.kubernetes.io/managed-by":"pulum|...
```

`kubectl apply -f t.yaml` succeeds, also if the date at the error position is double-quoted (`"2020-03-25T13:37:11Z"`) it succeeds.
