### ISSUE TITLE
Changing the apiVersion of resources with a user-specified name fails

### ISSUE THREAD

**Issue by RichardWLaub** [pulumi/pulumi-kubernetes#546]
I ran into this issue while trying to upgrade from istio 1.0.7 to 1.1.3. When upgrading the apiVersion of a resource pulumi will perform a `delete` and a `create` instead of a `replace`. This causes kuberntes to error.

To reproduce deploy a helm resource with the following as a template:

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
```

Then change it to this:
```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
```

The error will be:

```
Previewing update (helm):

     Type                                                    Name           Plan
     pulumi:pulumi:Stack                                     helm-helm
     └─ kubernetes:helm.sh:Chart                             test
 +      ├─ kubernetes:rbac.authorization.k8s.io:ClusterRole  secret-reader  create
 -      └─ kubernetes:rbac.authorization.k8s.io:ClusterRole  secret-reader  delete

Resources:
    + 1 to create
    - 1 to delete
    2 changes. 2 unchanged

Do you want to perform this update? yes
Updating (helm):

     Type                                                    Name           Status                  Info
     pulumi:pulumi:Stack                                     helm-helm      **failed**              1 error
     └─ kubernetes:helm.sh:Chart                             test
 +      └─ kubernetes:rbac.authorization.k8s.io:ClusterRole  secret-reader  **creating failed**     1 error

Diagnostics:
  kubernetes:rbac.authorization.k8s.io:ClusterRole (secret-reader):
    error: Plan apply failed: clusterroles.rbac.authorization.k8s.io "secret-reader" already exists

  pulumi:pulumi:Stack (helm-helm):
    error: update failed

Resources:
    2 unchanged

Duration: 2s
```
