### ISSUE TITLE
Resource missing from remote YAML config file

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-kubernetes#565]
The issue is that `ServiceAccount` `cert-manager-cainjector` does not show up during `pulumi preview`.

This is the snippet that interacts with the remote YAML config file.

```typescript
new k8s.yaml.ConfigFile('cert-manager', {
  file: 'https://raw.githubusercontent.com/jetstack/cert-manager/v0.7.2/deploy/manifests/cert-manager.yaml',
  transformations: [
    (resource: any) => {
      if (resource.kind == 'Deployment' && resource.metadata.name == 'cert-manager') {
        resource.spec.template.spec.containers[0].args.push(
          ...[
            '--default-issuer-name=letsencrypt',
            '--default-issuer-kind=ClusterIssuer',
            '--default-acme-issuer-challenge-type=dns01',
            '--default-acme-issuer-dns01-provider-name=route53'
          ]
        );

        resource.spec.template.spec.containers[0].env.push([
          {
            name: 'AWS_REGION',
            value: awsConfig.require('region')
          },
          {
            name: 'AWS_ACCESS_KEY_ID',
            value: awsAccessKey.id
          },
          {
            name: 'AWS_SECRET_ACCESS_KEY',
            value: awsAccessKey.secret
          }
        ]);
      }
    }
  ]
});
```

This is the resource that is skipped over.

```
---
---
# Source: cert-manager/charts/cainjector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-manager-cainjector
  namespace: "cert-manager"
  labels:
    app: cainjector
    chart: cainjector-v0.7.2
    release: cert-manager
    heritage: Tiller
```
