### ISSUE TITLE
 error: unable to load schema information from the API server 

### ISSUE THREAD

**Issue by KrisBuytaert** [pulumi/pulumi-kubernetes#869]
### Problem description

While going trough the infrastructure as code tutorial in the K8s section .. 
I bumped into 

error: unable to load schema information from the API server: Get https://127.0.0.1:6443/openapi/v2?timeout=32s: x509: certificate is valid for 10.96.0.1, 10.0.228.152, not 127.0.0.1

I have tunneld 6443 to localhost for this setup, kubectl get nodes works with the --insecure-skip-tls-verify 

So the question is how to insert that param into the config so that pulumi uses it.

**Comment by pgavlin** [comment]
cc @joeduffy @lblackstone

**Comment by lblackstone** [comment]
Pulumi doesn't currently expose the `insecure-skip-tls-verify` option through the SDK, but you should be able to set it in your KUBECONFIG for the cluster. For example:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: test-cluster
  cluster:
    insecure-skip-tls-verify: true
    server: https://127.0.0.1:6443
...
```
